use crate::device::config::{DeviceConfig, SocFamily, TouchProtocol};

pub fn legacy_devices() -> Vec<DeviceConfig> {
    use super::{fl_mxc, fl_mxc_aw99703, fl_mxc_lm3630a, fl_mxc_tlc5947};
    vec![
        DeviceConfig {
            codename: "trilogy",
            model: "Kobo Touch",
            soc: SocFamily::Nxp,
            display_dpi: 167,
            has_color_screen: false,
            has_natural_light: false,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Legacy,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "pixie",
            model: "Kobo Mini",
            soc: SocFamily::Nxp,
            display_dpi: 200,
            has_color_screen: false,
            has_natural_light: false,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Legacy,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "dragon",
            model: "Kobo Aura HD",
            soc: SocFamily::Nxp,
            display_dpi: 265,
            has_color_screen: false,
            has_natural_light: false,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "dahlia",
            model: "Kobo Aura H2O",
            soc: SocFamily::Nxp,
            display_dpi: 265,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: false,
            has_gsensor: true,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: false,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "alyssum",
            model: "Kobo Glo HD",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "pika",
            model: "Kobo Aura ONE",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc_lm3630a(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "star",
            model: "Kobo Aura SE",
            soc: SocFamily::Nxp,
            display_dpi: 212,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/bd71827_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "snow",
            model: "Kobo Aura",
            soc: SocFamily::Nxp,
            display_dpi: 212,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/bd71827_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "elipsa",
            model: "Kobo Elipsa",
            soc: SocFamily::Nxp,
            display_dpi: 227,
            has_color_screen: false,
            has_natural_light: false,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: true,
            is_smp: true,
            frontlight: fl_mxc_aw99703(false),
            battery_sysfs: "/sys/class/power_supply/battery".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "storm",
            model: "Kobo Forma 32GB",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: true,
            has_gsensor: true,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc_tlc5947(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: false,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: false,
        },
    ]
}
