// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nayeem Bin Ahsan
use crate::device::config::{DeviceConfig, SocFamily, TouchProtocol};

pub fn nxp_devices() -> Vec<DeviceConfig> {
    use super::{fl_mxc, fl_mxc_aw99703, fl_mxc_lm3630a, fl_mxc_tlc5947};
    vec![
        DeviceConfig {
            codename: "nova",
            model: "Kobo Clara HD",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc_lm3630a(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: false,
        },
        DeviceConfig {
            codename: "goldfinch",
            model: "Kobo Clara 2E",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: true,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: true,
            is_smp: false,
            frontlight: fl_mxc_aw99703(true),
            battery_sysfs: "/sys/class/power_supply/battery".into(),
            touch_protocol: TouchProtocol::Phoenix,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "io",
            model: "Kobo Libra 2",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: true,
            has_keys: true,
            has_gsensor: true,
            has_eclipse_wfm: true,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/bd71827_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: false,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "frost",
            model: "Kobo Forma",
            soc: SocFamily::Nxp,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: false,
            has_keys: true,
            has_gsensor: true,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc_tlc5947(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: false,
        },
        DeviceConfig {
            codename: "cadmus",
            model: "Kobo Sage",
            soc: SocFamily::Sunxi,
            display_dpi: 300,
            has_color_screen: false,
            has_natural_light: true,
            has_bt: true,
            has_keys: true,
            has_gsensor: true,
            has_eclipse_wfm: true,
            is_smp: true,
            frontlight: fl_mxc_aw99703(false),
            battery_sysfs: "/sys/class/power_supply/battery".into(),
            touch_protocol: TouchProtocol::Snow,
            touch_switch_xy: true,
            touch_mirrored_x: false,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "luna",
            model: "Kobo Nia",
            soc: SocFamily::Nxp,
            display_dpi: 212,
            has_color_screen: false,
            has_natural_light: false,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/bd71827_bat".into(),
            touch_protocol: TouchProtocol::Phoenix,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: true,
        },
        DeviceConfig {
            codename: "kraken",
            model: "Kobo Glo",
            soc: SocFamily::Nxp,
            display_dpi: 212,
            has_color_screen: false,
            has_natural_light: false,
            has_bt: false,
            has_keys: false,
            has_gsensor: false,
            has_eclipse_wfm: false,
            is_smp: false,
            frontlight: fl_mxc(),
            battery_sysfs: "/sys/class/power_supply/mc13892_bat".into(),
            touch_protocol: TouchProtocol::Legacy,
            touch_switch_xy: true,
            touch_mirrored_x: true,
            touch_mirrored_y: false,
            standby_state: "standby",
            automagic_sysfs: false,
        },
    ]
}
